title: My Patterns Jekyll Project (jQuery 3 / Webpack 4)
author: Your Name Here
baseurl: /
domain: myproject.example.com
media: /media
markdown: kramdown
permalink: /:title
sass:
  style: :compressed
  load_paths:
    - "_sass"
    - "patternslib"
    - "patternslib/_sass"
exclude: 
  - Gemfile
  - Gemfile.lock
  - config.codekit
  - config.rb
  - node_modules
  - patternslib/node_modules
  - Makefile
  - README.md
  - bundle-config.js
  - src/
  - stamp-npm
  - stamp-bundler
  - package.json
  - package-lock.json
  - npmshrinkwrap.json
  - webpack.config.js
patterns:
  - version: 4.0.0
  - components:
    - modal
    - avatar
    - equaliser
    - grid
  - basics: 
    - reset
    - clear-fix
